spring:
  profiles:
    include: secret
  config:
    import: oauth-secret.yml
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    enabled: true
    check-template-location: true


logging:
  level:
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO
      sqlonly: OFF
      sqltiming: INFO